### ISSUE TITLE
Colorpicker on group does not work

### ISSUE THREAD

**Issue by fsedarkalex** [igorgladkov/rotini#14]
If I try to use a group for a Colorpicker widget, setting a color does not work.

In normal sitemaps everything works fne but here:
2016-01-08 16:52:16.885 [WARN ] [o.i.r.i.resources.ItemResource] - Received HTTP POST request at 'items/g_rgb' with an invalid status value '231,655624,100,000000,59,215691'.

My setup:
    Frame label="Master {widget:light-color}" {
      Colorpicker item=g_rgb
    }

Working sitemap:
            Colorpicker item=g_rgb icon="switch"

**Comment by fsedarkalex** [comment]
I have to correct my report...
It seems not to be working AT ALL.
Tried with items directly:

2016-01-10 01:39:30.962 [WARN ] [o.i.r.i.resources.ItemResource] - Received HTTP POST request at 'items/rgb_ess2' with an invalid status value '115,529411,100,000000,100,000000'.

config:
sitemap:
        Frame label="RGB Essz 1 {widget:light-color}" {
          Colorpicker item=rgb_ess1
        }

item:
Color rgb_ess1 "Licht Esszimmer Tisch" (g_rgb_ess, g_rgb_main, g_rgb) {dmx="CHANNEL[13/3:500]"}

**Comment by d0t101101** [comment]
Note this IS working for me just fine.  I define a group of Philips hue bulbs like so in items:

  Group:Color Light_Group_Office "Office Lights [(%d)]" <hue> (GF_Office)
  Color COLOR_HUE_4 "Lamp 1" (Light_Group_Office ) {hue="4;brightness;30"}
  Color COLOR_HUE_7 "Lamp 2" (Light_Group_Office ) {hue="7;brightness;30"}

And then control the color of the group of bulbs in my rotini sitemap like so:

```
Frame label="Living {widget:light-color}" {
  Colorpicker item=Light_Group_Living
}
```

Hope this helps,
.

**Comment by fsedarkalex** [comment]
That is strange hope igor can get the bug out of our info. I would be happy to provide you with further information if you need

Am 10. Januar 2016 21:05:04 MEZ, schrieb d0t101101 notifications@github.com:

> Note this IS working for me just fine.  I define a group of Philips hue
> bulbs like so in items:
> 
> Group:Color Light_Group_Office "Office Lights [(%d)]" <hue> (GF_Office)
> Color COLOR_HUE_4 "Lamp 1" (Light_Group_Office )
> {hue="4;brightness;30"}
> Color COLOR_HUE_7 "Lamp 2" (Light_Group_Office )
> {hue="7;brightness;30"}
> 
> And then control the color of the group of bulbs in my rotini sitemap
> like so:
> 
>    Frame label="Living {widget:light-color}" {
>      Colorpicker item=Light_Group_Living
>    }
> 
> Hope this helps,
> .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/igorgladkov/rotini/issues/14#issuecomment-170387171

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by anordvall** [comment]
Same for me... I can not get the colorpicker widget to work. When trying it the log says:

Received HTTP POST request at 'items/RGBW' with an invalid status value '12,941176,100,000000,100,000000'.

**Comment by igorgladkov** [comment]
@anordvall Do use Group or single Item in widget config?

**Comment by anordvall** [comment]
Single item... but maybe it's best to ignore me in this case as I'm not even sure I've set up the color picker correctly in the first place. Although, it do work in the standard openHAB app.

**Comment by igorgladkov** [comment]
Figured out the issue, should be fixed in the next release

**Comment by frode** [comment]
Good, because I also get invalid config, although it is setup correctly, it was working in a previous version of the app with the same setup of the sitemap as it is now.

**Comment by frode** [comment]
Still getting invalid config on the light-color widget, which means the option to set a color will never get available, so it remains invalid?

**Comment by anordvall** [comment]
For me it works with the latest client update.

**Comment by igorgladkov** [comment]
@frode I actually didn't notice you were talking about invalid config as well, since this issue was originally about modifying color. Can you open another issue and provide your sitemap/item configs. Thanks
