### ISSUE TITLE
Widgets does not fill 100% of vertical space in full screen mode

### ISSUE THREAD

**Issue by anordvall** [igorgladkov/rotini#21]
When in full screen mode, the widgets does currently not fill 100% of the vertical space.

**Comment by igorgladkov** [comment]
This has been addressed. No need for extra configuration either. Widget tiles will snap to screen edge vertically (unless vertical is too small to fit at least 2 rows), so if number of rows is the same as a size of the screen (e.g. no scroll), it will always fill 100%

**Comment by anordvall** [comment]
I still can't get it to work. Looks the same as before. Any idea what I can do to "debug"? :)
![2016-01-14 20 45 16](https://cloud.githubusercontent.com/assets/13090236/12337266/46eb3010-bb09-11e5-99a0-74ef24df6a8f.png)

**Comment by igorgladkov** [comment]
@anordvall Are you 100% sure that this is the latest version?

**Comment by anordvall** [comment]
Yes I updated it minutes ago... then I killed the app to be sure and started it again. No version number within the app?

**Comment by igorgladkov** [comment]
No version number yet. What phone is this?

**Comment by anordvall** [comment]
Samsung Galaxy S4. I can confirm the same version of the app contains the fix for the Tasker crash..

**Comment by igorgladkov** [comment]
Reproduced the issue on a Samsung/5.0.1. Opened https://github.com/igorgladkov/rotini/issues/42 to track
